add_subdirectory(net)
add_subdirectory(ta)
add_subdirectory(fin)
add_subdirectory(ts)
add_subdirectory(sqlite)
add_subdirectory(mapper)
add_subdirectory(img)
add_subdirectory(coro)
add_subdirectory(parser)
add_subdirectory(crypto)
add_subdirectory(hash)
add_subdirectory(fuzzy)
add_subdirectory(rules_forge)
add_subdirectory(os)
# add_subdirectory(wasm)
