#ifndef exprtk_TYPES_H
#define exprtk_TYPES_H

#include "turbo_buffer.h"
#include "turbo_str_view.h"
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
// Token types (used by Lexer -> Parser)
// Note: Actual token IDs are generated by Lemon, but we might arguably not need this enum
// if we only use Lemon's defines. However, for the lexer generic return or debug, it's useful.
// We will rely on Lemon generic integer for token IDs mostly.

typedef enum {
  EXPRTK_NODE_NUMBER,
  EXPRTK_NODE_INTEGER,
  EXPRTK_NODE_VARIABLE,
  EXPRTK_NODE_BINARY_OP,
  EXPRTK_NODE_FUNCTION_CALL,
  EXPRTK_NODE_ASSIGNMENT,
  EXPRTK_NODE_IF,
  EXPRTK_NODE_WHILE,
  EXPRTK_NODE_FOR,
  EXPRTK_NODE_SPREAD,
  EXPRTK_NODE_BLOCK,
  EXPRTK_NODE_FLOW,
  EXPRTK_NODE_STRING,
  EXPRTK_NODE_VECTOR,
  EXPRTK_NODE_INDEX,
  EXPRTK_NODE_SLICE,
  EXPRTK_NODE_FUNCTION_DEFINITION,
  EXPRTK_NODE_MEMBER_CALL,
  EXPRTK_NODE_CONSTANT_DECL,
  EXPRTK_NODE_SWITCH,
  EXPRTK_NODE_DO_WHILE,
  EXPRTK_NODE_MAP_LITERAL,
  EXPRTK_NODE_MEMBER_ACCESS,
  EXPRTK_NODE_MEMBER_SET,
  EXPRTK_NODE_FOR_IN,
  EXPRTK_NODE_NULL,
  EXPRTK_NODE_TEMPLATE_STRING,
  EXPRTK_NODE_DESTRUCTURING_ASSIGNMENT,
  EXPRTK_NODE_REST_PARAMETER,
  EXPRTK_NODE_TRY_CATCH,
  EXPRTK_NODE_THROW,
  EXPRTK_NODE_FUNCTION_EXPRESSION,
  EXPRTK_NODE_YIELD,              // yield 表达式
  EXPRTK_NODE_GENERATOR_FUNCTION, // func* 生成器函数定义
  // OOP nodes
  EXPRTK_NODE_CLASS_DEF,          // class 定义
  EXPRTK_NODE_METHOD,             // 方法定义
  EXPRTK_NODE_FIELD_DECL,         // 字段声明
  EXPRTK_NODE_NEW,                // new 表达式 (实例化)
  EXPRTK_NODE_THIS,               // this 关键字
  EXPRTK_NODE_SUPER,              // super 关键字
  EXPRTK_NODE_INSTANCEOF          // instanceof 操作符
} exprtk_node_type_t;

typedef struct exprtk_node_s exprtk_node_t;

struct exprtk_node_s {
  exprtk_node_type_t type;
  mem_pool_t *arena;
  int line;
  int column;
  int inferred_type; // Type inference result: EXPRTK_VAL_* or -1 if unknown
  union {
    double number;
    int64_t integer;
    struct {
      char *name;
    } variable;
    struct {
      int op; // Token ID
      exprtk_node_t *left;
      exprtk_node_t *right;
    } binary;
    struct {
      char *name;
      exprtk_node_t **args;
      size_t arg_count;
    } function;
    struct {
      char *name;
      exprtk_node_t *value; // For assignment: var := value
    } assignment;
    struct {
      exprtk_node_t *condition;
      exprtk_node_t *if_branch;
      exprtk_node_t *else_branch;
    } if_stmt;
    struct {
      exprtk_node_t *condition;
      exprtk_node_t *body;
    } while_loop;
    struct {
      exprtk_node_t *init;
      exprtk_node_t *condition;
      exprtk_node_t *post;
      exprtk_node_t *body;
    } for_loop;
    struct {
      exprtk_node_t **statements;
      size_t count;
    } block;
    struct {
      int type;             // exprtk_TOKEN_BREAK, _CONTINUE, _RETURN
      exprtk_node_t *value; // for return
    } flow;
    struct {
      tstr_v value;
    } string;
    struct {
      exprtk_node_t **elements;
      size_t count;
    } vector;
    struct {
      exprtk_node_t *array;
      exprtk_node_t *index;
    } index_access;
    struct {
      exprtk_node_t *array;
      exprtk_node_t *start;
      exprtk_node_t *end;
    } slice;
    struct {
      char *name;
      exprtk_node_t **arg_params;
      size_t arg_count;
      exprtk_node_t *body;
    } func_def;
    struct {
      exprtk_node_t *object;
      char *method;
      exprtk_node_t **args;
      size_t arg_count;
    } member_call;
    struct {
      exprtk_node_t *value;
      exprtk_node_t **cases; // format: [case_val1, body1, case_val2, body2, ...]
      size_t case_count;     // number of cases * 2 == length of cases array
      exprtk_node_t *default_case;
    } switch_stmt;
    struct {
      exprtk_node_t *body;
      exprtk_node_t *condition;
    } do_while;
    struct {
      char **keys;
      exprtk_node_t **values;
      size_t count;
    } map_literal;
    struct {
      exprtk_node_t *object;
      char *member;
    } member_access;
    struct {
      exprtk_node_t *object;
      char *member;
      exprtk_node_t *value;
    } member_set;
    struct {
      char *var_name;
      exprtk_node_t *collection;
      exprtk_node_t *body;
    } for_in;
    struct {
      char *template_str;
      size_t len;
    } template_string;
    struct {
      exprtk_node_t *child;
    } spread;
    struct {
      exprtk_node_t *targets; // EXPRTK_NODE_VECTOR or EXPRTK_NODE_MAP_LITERAL
      exprtk_node_t *value;
      int is_constant;
    } destructuring;
    struct {
      exprtk_node_t *try_body;
      char *catch_var; // variable name for the caught error
      exprtk_node_t *catch_body;
    } try_catch;
    struct {
      exprtk_node_t *value; // expression to throw
    } throw_stmt;
    struct {
      exprtk_node_t *value; // yield 的值（可为 NULL）
    } yield_expr;
    struct {
      char *name;
      exprtk_node_t **arg_params;
      size_t arg_count;
      exprtk_node_t *body;
    } generator_def;
    // OOP node data
    struct {
      char *name;                      // 类名
      exprtk_node_t *constructor;      // 构造函数节点 (EXPRTK_NODE_FUNCTION_DEFINITION)
      exprtk_node_t **methods;         // 方法节点数组
      size_t method_count;
      exprtk_node_t **static_methods;  // 静态方法数组
      size_t static_method_count;
      char *parent_name;               // 父类名 (extends 后的类名, NULL = 无继承)
      char **interface_names;          // implements 后的接口名数组
      size_t interface_count;
      int is_abstract;                 // 是否为 abstract class
      int is_interface;                // 是否为 interface
      int is_final;                    // 是否禁止继承
    } class_def;
    struct {
      char *name;                      // 方法名
      exprtk_node_t **arg_params;      // 参数
      size_t arg_count;
      exprtk_node_t *body;             // 方法体
      int is_static;                   // 是否为静态方法
      int is_abstract;                 // 是否为 abstract method
      int access_level;                // public/protected/private
      int is_override;                 // 是否要求重写父类方法
      int is_final;                    // 是否禁止子类重写
    } method;
    struct {
      char *name;                      // 字段名
      exprtk_node_t *initializer;      // 初始值表达式，可为 NULL
      int is_static;                   // 是否为静态字段
      int access_level;                // public/protected/private
    } field_decl;
    struct {
      char *class_name;                // 要实例化的类名
      exprtk_node_t **args;            // 构造函数参数
      size_t arg_count;
    } new_expr;
    struct {
      char *member;                    // super 后的成员名 (NULL 表示 super())
      exprtk_node_t **args;            // 参数 (仅用于 super())
      size_t arg_count;
      int is_call;                     // 是否为 super.method(...) 调用
    } super_expr;
    struct {
      exprtk_node_t *object;           // instanceof 左侧对象
      char *class_name;                // instanceof 右侧类名
      exprtk_node_t *class_expr;       // instanceof 右侧 class value 表达式
    } instanceof_expr;
  } data;
};

typedef struct {
  double *data;
  size_t size;
} exprtk_vector_t;

// Forward declaration for map
struct exprtk_map_entry_s;
struct exprtk_map_s;

typedef enum {
  EXPRTK_VAL_NUMBER,
  EXPRTK_VAL_STRING,
  EXPRTK_VAL_INTEGER,
  EXPRTK_VAL_VECTOR,
  EXPRTK_VAL_MAP,
  EXPRTK_VAL_NULL,
  EXPRTK_VAL_LIST,
  EXPRTK_VAL_FUNCTION,
  EXPRTK_VAL_COROUTINE,     // 协程对象
  // OOP value types
  EXPRTK_VAL_CLASS,         // 类对象
  EXPRTK_VAL_INSTANCE,      // 实例对象
  EXPRTK_VAL_BOUND_METHOD   // 绑定了 this 的方法
} exprtk_value_type_t;

typedef enum {
  EXPRTK_ACCESS_PUBLIC = 0,
  EXPRTK_ACCESS_PROTECTED = 1,
  EXPRTK_ACCESS_PRIVATE = 2
} exprtk_access_level_t;

// Evaluation result type
typedef struct exprtk_value_s {
  exprtk_value_type_t type;
  union {
    double number;
    tstr_v string;
    int64_t integer;
    exprtk_vector_t vector;
    struct {
      void *htab; // HTAB(exprtk_map_kv_t)* — O(1) lookup
    } map;
    struct {
      struct exprtk_value_s *items;
      size_t count;
      size_t capacity;
      int heap_owned;
    } list;
    struct {
      exprtk_node_t **arg_params; // parameter nodes
      size_t arg_count;
      exprtk_node_t *body;
      struct exprtk_env_s *closure_env; // captured scope
      struct exprtk_class_s *owner_class;
      int is_static_method;
      int access_level;
      int is_override;
      int is_final;
    } function;
    struct {
      struct exprtk_coroutine_s *coro; // 协程实例指针
    } coroutine;
    // OOP value data
    struct {
      struct exprtk_class_s *klass;    // 类对象指针
    } class_val;
    struct {
      struct exprtk_instance_s *instance; // 实例对象指针
    } instance_val;
    struct {
      struct exprtk_instance_s *instance; // this 对象
      struct exprtk_func_s *method;       // 方法函数
    } bound_method_val;
  } data;
} exprtk_value_t;

// Map entry (key-value pair) — defined after exprtk_value_t
typedef struct exprtk_map_entry_s {
  char *key;
  exprtk_value_t value;
} exprtk_map_entry_t;

typedef exprtk_value_t (*exprtk_native_fn)(size_t arg_count, exprtk_value_t *args, void *user_data);

typedef struct exprtk_func_s {
  char *name;
  int is_script;
  struct exprtk_class_s *owner_class;
  struct exprtk_env_s *closure_env;
  int is_static_method;
  int access_level;
  int is_override;
  int is_final;
  union {
    struct {
      exprtk_native_fn fn;
      void *user_data;
    } native;
    struct {
      exprtk_node_t **arg_params;
      size_t arg_count;
      exprtk_node_t *body;
    } script;
  } data;
  struct exprtk_func_s *next;
} exprtk_func_t;

typedef enum {
  exprtk_FLOW_NORMAL,
  exprtk_FLOW_BREAK,
  exprtk_FLOW_CONTINUE,
  exprtk_FLOW_RETURN,
  exprtk_FLOW_THROW,
  exprtk_FLOW_YIELD      // 协程 yield - 暂停执行并返回
} exprtk_flow_t;

typedef struct exprtk_module_s exprtk_module_t;
struct exprtk_env_s;
struct exprtk_func_s;
typedef exprtk_value_t (*exprtk_eval_node_fn)(const exprtk_node_t *node,
                                              struct exprtk_env_s *env);
typedef int (*exprtk_exec_script_body_fn)(struct exprtk_func_s *func,
                                          struct exprtk_env_s *local_env,
                                          struct exprtk_env_s *caller_env,
                                          exprtk_value_t *out);

typedef struct exprtk_env_s {
  void *vars; // Hash table for variables (opaque pointer to HTAB(exprtk_var_entry_t)*)
  exprtk_func_t *funcs;
  exprtk_flow_t flow;
  exprtk_value_t return_value;
  struct exprtk_env_s *parent;

  // Per-env static modules (mounted via exprtk_env_add_module)
  const exprtk_module_t **modules;
  size_t module_count;
  struct exprtk_class_s *current_class;
  int current_method_is_static;
  int current_method_is_constructor;

  // Sorted cache of all module entries (built on first call, O(log n) lookup)
  void *mod_cache; // exprtk_func_entry_t* sorted array (opaque)
  size_t mod_cache_count;

  // User data pointer for custom context (e.g., universe_t, strategy state)
  void *user_data;
  void *regex_ctx;
  exprtk_eval_node_fn eval_node;
  exprtk_exec_script_body_fn exec_script_body;

  // Safety Limits
  uint32_t max_recursion;
  uint32_t curr_recursion;
  uint32_t max_loop_iterations;
  uint32_t curr_loop_iterations;
  uint32_t max_nodes; // Max nodes to evaluate per expression
  uint32_t curr_nodes;
  int aborted;                       // Set to 1 if any safety limit is exceeded
  int last_line;                     // Line of last evaluated node
  int last_column;                   // Column of last evaluated node
  mem_pool_t arena;                // For persistent data like script function bodies
  exprtk_value_t error_value;        // Value thrown by throw statement
  struct exprtk_env_s *next_closure; // linked list of closure scopes to free

  // Error reporting (Phase 2)
  char error_msg[256]; // Last error message
  int error_line;      // Line where error occurred
  int error_column;    // Column where error occurred
} exprtk_env_t;

// Simple context for parser
typedef struct {
  exprtk_node_t *root;
  int error;
  int fatal_error;
  char error_msg[256];
  mem_pool_t *arena;
} exprtk_parse_ctx_t;

// Token structure passed from Lexer to Parser
typedef struct {
  int type; // Token ID (from Lemon)
  const char *start;
  size_t length;
  double num_value; // For numbers
  int line;
  int column;
} exprtk_token_t;

/* =========================================================================
 * Coroutine Support
 * ========================================================================= */

typedef enum {
  EXPRTK_CORO_CREATED,   // 已创建，未启动
  EXPRTK_CORO_RUNNING,   // 正在运行
  EXPRTK_CORO_SUSPENDED, // 已挂起（yield）
  EXPRTK_CORO_DONE       // 已完成
} exprtk_coro_state_t;

/**
 * @brief 协程栈帧（用于保存/恢复执行状态）
 */
typedef struct exprtk_coro_frame_s {
  exprtk_node_t *node;           // 当前执行节点
  size_t block_index;            // 块内语句索引
  size_t loop_iteration;         // 循环迭代计数
  struct exprtk_coro_frame_s *next; // 链表下一个
} exprtk_coro_frame_t;

/**
 * @brief 协程实例
 */
typedef struct exprtk_coroutine_s {
  // 协程状态
  exprtk_coro_state_t state;
  
  // 执行上下文
  exprtk_env_t *env;              // 协程的环境（变量作用域）
  exprtk_node_t *body;            // 函数体
  exprtk_coro_frame_t *frames;    // 调用栈帧链表
  
  // 值传递
  exprtk_value_t yielded_value;   // yield 的值
  exprtk_value_t sent_value;      // send() 传入的值
  int has_sent_value;             // 是否有 send 值
  
  // 内存管理
  mem_pool_t arena;               // 协程私有内存池
  
  // 引用计数（用于自动释放）
  int ref_count;
} exprtk_coroutine_t;

#ifdef __cplusplus
}
#endif

#endif // exprtk_TYPES_H
