#include "turbo_script_timer.h"
#include "exprtk.h"
#include "salts_cron.h"
#include <limits.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
enum { TS_TIMER_MAX_CAPACITY=65536, TS_TIMER_ERROR_SIZE=256 };
#define TS_TIMER_MAX_DELAY_MS ((uint64_t)UINT_MAX-1U)
typedef enum { T_EMPTY,T_RESERVED,T_SCHEDULED,T_PENDING,T_RUNNING,T_COMPLETED,T_CANCELLED,T_FAILED } tstate;
typedef enum { T_AFTER,T_EVERY,T_CRON } tkind;
typedef struct ts_timer_job_s { struct ts_timer_scheduler_s*s;int64_t id;tkind kind;tstate state;int active,cancelled,await_active;salts_coro_executor_await_t await;uint64_t interval;salts_cron_expr_t cron;time_t due;exprtk_value_t callback;char error[TS_TIMER_ERROR_SIZE]; } tjob;
struct ts_timer_scheduler_s { turbo_script_ctx_t*ctx;salts_mutex_t mutex;tjob*jobs;size_t capacity,active_count;int64_t next_id;int closing;};
static int term(tstate s){return s==T_COMPLETED||s==T_CANCELLED||s==T_FAILED||s==T_EMPTY;}static const char*name(tstate s){static const char*n[]={"invalid","reserved","scheduled","pending","running","completed","cancelled","failed"};return s<8?n[s]:"invalid";}static void cp(char*d,size_t n,const char*m){if(d&&n)snprintf(d,n,"%s",m?m:"");}static void failctx(turbo_script_ctx_t*c,turbo_script_error_code_t e,const char*m){c->error_code=e;cp(c->error_msg,sizeof(c->error_msg),m);c->env.aborted=1;cp(c->env.error_msg,sizeof(c->env.error_msg),m);}static void dropcb(tjob*j){if(j->callback.type==EXPRTK_VAL_FUNCTION&&j->callback.ownership==EXPRTK_VALUE_OWNED&&j->callback.data.function.closure_env){exprtk_env_release(j->callback.data.function.closure_env);j->callback.data.function.closure_env=NULL;j->callback.ownership=EXPRTK_VALUE_BORROWED;}}static void keepcb(tjob*j){if(j->callback.type==EXPRTK_VAL_FUNCTION&&j->callback.data.function.closure_env){exprtk_env_retain(j->callback.data.function.closure_env);j->callback.ownership=EXPRTK_VALUE_OWNED;}}
static int val_u64(exprtk_value_t v,uint64_t*o){if(v.type==EXPRTK_VAL_INTEGER&&v.data.integer>=0){*o=v.data.integer;return 0;}if(v.type==EXPRTK_VAL_NUMBER&&isfinite(v.data.number)&&v.data.number>=0&&floor(v.data.number)==v.data.number&&v.data.number<=(double)UINT64_MAX){*o=(uint64_t)v.data.number;return 0;}return -1;}static int val_id(exprtk_value_t v,int64_t*o){uint64_t n;if(val_u64(v,&n)||!n||n>INT64_MAX)return -1;*o=(int64_t)n;return 0;}static tjob*find(ts_timer_scheduler_t*s,int64_t id){for(size_t i=0;i<s->capacity;i++)if(s->jobs[i].id==id&&s->jobs[i].state!=T_EMPTY)return&s->jobs[i];return NULL;}static void inactive(ts_timer_scheduler_t*s,tjob*j){if(j->active){j->active=0;if(s->active_count)s->active_count--;}}
static uint32_t due_ms(time_t due){time_t now=time(NULL);if(due<=now)return 1;uint64_t sec=(uint64_t)(due-now);return sec>TS_TIMER_MAX_DELAY_MS/1000?TS_TIMER_MAX_DELAY_MS:(uint32_t)(sec*1000);}
static int cancelled(tjob*j){int r;salts_mutex_lock(&j->s->mutex);r=j->cancelled;salts_mutex_unlock(&j->s->mutex);return r;}
static int request(tjob*j){salts_coro_executor_await_t h={0};int wake=0;salts_mutex_lock(&j->s->mutex);if(term(j->state)||j->cancelled){salts_mutex_unlock(&j->s->mutex);return SALTS_EALREADY;}j->cancelled=1;j->state=T_CANCELLED;inactive(j->s,j);if(j->await_active){h=j->await;wake=1;}salts_mutex_unlock(&j->s->mutex);if(wake)(void)salts_coro_executor_await_complete(j->s->ctx->executor,h,SALTS_ECANCELED);return SALTS_OK;}
static int wait(tjob*j,uint32_t ms){salts_coro_executor_await_t h={0};int status=0,rc=salts_coro_executor_await_begin(&h);if(rc)return rc;salts_mutex_lock(&j->s->mutex);j->await=h;j->await_active=1;j->state=j->cancelled?T_CANCELLED:T_SCHEDULED;int stop=j->cancelled;salts_mutex_unlock(&j->s->mutex);if(stop)(void)salts_coro_executor_await_complete(j->s->ctx->executor,h,SALTS_ECANCELED);rc=salts_coro_executor_await_for(h,ms?ms:1,&status);salts_mutex_lock(&j->s->mutex);j->await_active=0;if(!term(j->state))j->state=T_PENDING;stop=j->cancelled;salts_mutex_unlock(&j->s->mutex);return rc?rc:(stop||status==SALTS_ECANCELED?SALTS_ECANCELED:SALTS_OK);}
static void done(tjob*j,tstate state,const char*err){salts_mutex_lock(&j->s->mutex);j->await_active=0;j->state=state;if(err)cp(j->error,sizeof(j->error),err);inactive(j->s,j);salts_mutex_unlock(&j->s->mutex);dropcb(j);}
static void timer_run(coro_t*co,void*arg){tjob*j=arg;turbo_script_ctx_t*c;(void)co;if(!j||!j->s)return;c=j->s->ctx;for(;;){if(cancelled(j)||j->s->closing||atomic_load(&c->closing)){done(j,T_CANCELLED,"timer was cancelled");return;}uint32_t ms=j->kind==T_CRON?due_ms(j->due):(uint32_t)j->interval;if(wait(j,ms)!=SALTS_OK){done(j,T_CANCELLED,"timer was cancelled");return;}salts_mutex_lock(&j->s->mutex);if(j->cancelled){salts_mutex_unlock(&j->s->mutex);done(j,T_CANCELLED,"timer was cancelled");return;}j->state=T_RUNNING;salts_mutex_unlock(&j->s->mutex);c->env.aborted=0;c->env.flow=exprtk_FLOW_NORMAL;c->env.curr_nodes=c->env.curr_loop_iterations=c->env.curr_recursion=0;c->env.error_msg[0]='\0';exprtk_value_t r=exprtk_call_function_value(j->callback,0,NULL,&c->env);if(exprtk_value_is_object_like(&r))exprtk_map_free(&r);if(c->env.aborted||c->env.flow!=exprtk_FLOW_NORMAL){char e[TS_TIMER_ERROR_SIZE];cp(e,sizeof(e),c->env.error_msg[0]?c->env.error_msg:"timer callback failed");c->env.aborted=0;c->env.flow=exprtk_FLOW_NORMAL;done(j,T_FAILED,e);return;}exprtk_env_sweep_closures(&c->env);if(j->kind==T_AFTER){done(j,T_COMPLETED,NULL);return;}if(j->kind==T_CRON&&salts_cron_next(&j->cron,time(NULL),&j->due)!=SALTS_CRON_OK){done(j,T_FAILED,"timer: no next cron occurrence");return;}}}
static void timer_cancel(void*arg,int status){tjob*j=arg;(void)status;if(j)done(j,T_CANCELLED,"timer was cancelled");}
static int start(turbo_script_ctx_t*c,tkind kind,uint64_t interval,const salts_cron_expr_t*cron,time_t due,exprtk_value_t cb,int64_t*out){ts_timer_scheduler_t*s=c?c->timer_scheduler:NULL;tjob*j=NULL;if(!s||!c->executor){failctx(c,TURBO_SCRIPT_ERROR_STATE,"timer: executor is unavailable");return -1;}if(cb.data.function.closure_env){exprtk_env_t*r=cb.data.function.closure_env;while(r->parent&&r->parent!=&c->env)r=r->parent;if(r!=&c->env&&!r->parent)r->parent=&c->env;}salts_mutex_lock(&s->mutex);if(s->closing||atomic_load(&c->closing)){salts_mutex_unlock(&s->mutex);failctx(c,TURBO_SCRIPT_ERROR_STATE,"timer: context is closing");return -1;}for(size_t i=0;i<s->capacity;i++)if(term(s->jobs[i].state)){j=&s->jobs[i];break;}if(!j){salts_mutex_unlock(&s->mutex);failctx(c,TURBO_SCRIPT_ERROR_STATE,"timer: job capacity exhausted");return -1;}memset(j,0,sizeof(*j));j->s=s;j->id=++s->next_id;if(j->id<=0)j->id=s->next_id=1;j->kind=kind;j->interval=interval;j->due=due;if(cron)j->cron=*cron;j->callback=cb;keepcb(j);j->active=1;j->state=T_SCHEDULED;s->active_count++;*out=j->id;salts_mutex_unlock(&s->mutex);salts_coro_executor_task_t t={timer_run,timer_cancel,NULL,j};int rc=salts_coro_executor_try_submit_to(c->executor,0,&t);if(rc==SALTS_OK)return 0;salts_mutex_lock(&s->mutex);inactive(s,j);j->state=T_FAILED;cp(j->error,sizeof(j->error),"timer: executor rejected callback");salts_mutex_unlock(&s->mutex);dropcb(j);failctx(c,rc==SALTS_ENOMEM?TURBO_SCRIPT_ERROR_OOM:TURBO_SCRIPT_ERROR_STATE,"timer: executor queue is full");return -1;}
static exprtk_value_t after(size_t n,exprtk_value_t*a,exprtk_env_t*e,void*d){turbo_script_ctx_t*c=d;uint64_t ms;int64_t id;(void)e;if(n!=2||val_u64(a[0],&ms)||ms>TS_TIMER_MAX_DELAY_MS||a[1].type!=EXPRTK_VAL_FUNCTION){failctx(c,TURBO_SCRIPT_ERROR_ARGUMENT,"timer.after: expected (integer milliseconds, function)");return exprtk_val_num(0);}return start(c,T_AFTER,ms,NULL,0,a[1],&id)?exprtk_val_num(0):exprtk_val_int(id);}static exprtk_value_t every(size_t n,exprtk_value_t*a,exprtk_env_t*e,void*d){turbo_script_ctx_t*c=d;uint64_t ms;int64_t id;(void)e;if(n!=2||val_u64(a[0],&ms)||!ms||ms>TS_TIMER_MAX_DELAY_MS||a[1].type!=EXPRTK_VAL_FUNCTION){failctx(c,TURBO_SCRIPT_ERROR_ARGUMENT,"timer.every: expected (positive integer milliseconds, function)");return exprtk_val_num(0);}return start(c,T_EVERY,ms,NULL,0,a[1],&id)?exprtk_val_num(0):exprtk_val_int(id);}static exprtk_value_t cronfn(size_t n,exprtk_value_t*a,exprtk_env_t*e,void*d){turbo_script_ctx_t*c=d;salts_cron_expr_t x;time_t due;int64_t id;char err[TS_TIMER_ERROR_SIZE];(void)e;if(n!=2||a[0].type!=EXPRTK_VAL_STRING||a[1].type!=EXPRTK_VAL_FUNCTION){failctx(c,TURBO_SCRIPT_ERROR_ARGUMENT,"timer.cron: expected (cron expression, function)");return exprtk_val_num(0);}char*text=vstr_to_arena(a[0].data.string,&c->scratch_arena);if(!text||salts_cron_parse_ex(text,&x,err,sizeof(err))!=SALTS_CRON_OK||salts_cron_next(&x,time(NULL),&due)!=SALTS_CRON_OK){failctx(c,TURBO_SCRIPT_ERROR_ARGUMENT,"timer.cron: invalid expression");return exprtk_val_num(0);}return start(c,T_CRON,0,&x,due,a[1],&id)?exprtk_val_num(0):exprtk_val_int(id);}
static exprtk_value_t cancel(size_t n,exprtk_value_t*a,exprtk_env_t*e,void*d){turbo_script_ctx_t*c=d;int64_t id;(void)e;if(n!=1||val_id(a[0],&id)){failctx(c,TURBO_SCRIPT_ERROR_ARGUMENT,"timer.cancel: expected a positive timer id");return exprtk_val_num(0);}salts_mutex_lock(&c->timer_scheduler->mutex);tjob*j=find(c->timer_scheduler,id);salts_mutex_unlock(&c->timer_scheduler->mutex);return exprtk_val_bool(j&&request(j)==SALTS_OK);}static exprtk_value_t status(size_t n,exprtk_value_t*a,exprtk_env_t*e,void*d){turbo_script_ctx_t*c=d;int64_t id;const char*r="invalid";(void)e;if(n!=1||val_id(a[0],&id)){failctx(c,TURBO_SCRIPT_ERROR_ARGUMENT,"timer.status: expected a positive timer id");return exprtk_val_num(0);}salts_mutex_lock(&c->timer_scheduler->mutex);tjob*j=find(c->timer_scheduler,id);if(j)r=name(j->state);salts_mutex_unlock(&c->timer_scheduler->mutex);return exprtk_val_str(vstr_from_cstr(r));}
int ts_timer_scheduler_init(turbo_script_ctx_t*c,size_t cap){if(!c||!cap||cap>TS_TIMER_MAX_CAPACITY)return -1;ts_timer_scheduler_t*s=calloc(1,sizeof(*s));if(!s)return -1;s->jobs=calloc(cap,sizeof(*s->jobs));if(!s->jobs){free(s);return -1;}s->ctx=c;s->capacity=cap;salts_mutex_init(&s->mutex);for(size_t i=0;i<cap;i++)s->jobs[i].s=s;c->timer_scheduler=s;return 0;}void ts_timer_scheduler_shutdown(turbo_script_ctx_t*c){if(!c||!c->timer_scheduler)return;ts_timer_scheduler_t*s=c->timer_scheduler;salts_mutex_lock(&s->mutex);s->closing=1;salts_mutex_unlock(&s->mutex);for(size_t i=0;i<s->capacity;i++)(void)request(&s->jobs[i]);}void ts_timer_scheduler_destroy(turbo_script_ctx_t*c){if(!c||!c->timer_scheduler)return;ts_timer_scheduler_t*s=c->timer_scheduler;for(size_t i=0;i<s->capacity;i++)dropcb(&s->jobs[i]);salts_mutex_destroy(&s->mutex);free(s->jobs);free(s);c->timer_scheduler=NULL;}void ts_timer_register_functions(turbo_script_ctx_t*c){exprtk_env_register_func(&c->env,"timer.after",after,c);exprtk_env_register_func(&c->env,"timer.every",every,c);exprtk_env_register_func(&c->env,"timer.cron",cronfn,c);exprtk_env_register_func(&c->env,"timer.cancel",cancel,c);exprtk_env_register_func(&c->env,"timer.status",status,c);}int turbo_script_set_timer_capacity(turbo_script_ctx_t*c,size_t cap){if(!c||!c->timer_scheduler||!cap||cap>TS_TIMER_MAX_CAPACITY)return -1;if(turbo_script_timer_active_count(c))return -1;ts_timer_scheduler_destroy(c);return ts_timer_scheduler_init(c,cap)?-1:0;}size_t ts_timer_scheduler_capacity(turbo_script_ctx_t*c){return c&&c->timer_scheduler?c->timer_scheduler->capacity:0;}size_t turbo_script_timer_active_count(turbo_script_ctx_t*c){if(!c||!c->timer_scheduler)return 0;ts_timer_scheduler_t*s=c->timer_scheduler;salts_mutex_lock(&s->mutex);size_t n=s->active_count;salts_mutex_unlock(&s->mutex);return n;}size_t turbo_script_timer_failed_count(turbo_script_ctx_t*c){size_t n=0;if(!c||!c->timer_scheduler)return 0;ts_timer_scheduler_t*s=c->timer_scheduler;salts_mutex_lock(&s->mutex);for(size_t i=0;i<s->capacity;i++)n+=s->jobs[i].state==T_FAILED;salts_mutex_unlock(&s->mutex);return n;}
