#include "turbo_script_task.h"
#include "exprtk.h"
#include "salts_thread.h"
#include <limits.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

enum { TS_TASK_MAX_CAPACITY = 65536, TS_TASK_ERROR_SIZE = 256 };
#define TS_TASK_MAGIC UINT64_C(0x54535441534B4A4F)
#define TS_TASK_MAX_SLEEP_MS ((uint64_t)UINT_MAX - 1U)
typedef enum { TS_TASK_EMPTY, TS_TASK_RESERVED, TS_TASK_SCHEDULED, TS_TASK_RUNNING,
               TS_TASK_WAITING, TS_TASK_CANCELLING, TS_TASK_COMPLETED, TS_TASK_FAILED,
               TS_TASK_CANCELLED } ts_task_state_t;
typedef struct ts_task_job_s {
  uint64_t magic; struct ts_task_scheduler_s *scheduler; int64_t id; ts_task_state_t state;
  int active, cancelled, await_active, native_failed, auto_release, env_initialized;
  salts_coro_executor_await_t await_handle;
  exprtk_value_t callback, result; exprtk_env_t env;
  ts_task_completion_fn completion; void *completion_arg; char error[TS_TASK_ERROR_SIZE];
} ts_task_job_t;
struct ts_task_scheduler_s { turbo_script_ctx_t *ctx; salts_mutex_t mutex; ts_task_job_t *jobs;
  size_t capacity, active_count; int64_t next_id; int closing; };
static SALTS_THREAD_LOCAL ts_task_job_t *ts_task_current_job;

static int terminal(ts_task_state_t s) { return s >= TS_TASK_COMPLETED; }
static const char *state_name(ts_task_state_t s) { static const char *n[]={"invalid","reserved","scheduled","running","waiting","cancelling","completed","failed","cancelled"}; return s < sizeof(n)/sizeof(n[0]) ? n[s] : "invalid"; }
static void copy_error(char *d,size_t n,const char *m) { if(d&&n) snprintf(d,n,"%s",m?m:""); }
static void ctx_error(turbo_script_ctx_t *c,turbo_script_error_code_t e,const char *m){c->error_code=e;copy_error(c->error_msg,sizeof(c->error_msg),m);}
static ts_task_job_t *current(turbo_script_ctx_t *c){return ts_task_current_job&&ts_task_current_job->scheduler->ctx==c?ts_task_current_job:NULL;}
exprtk_env_t *ts_task_execution_env(turbo_script_ctx_t *c){ts_task_job_t*j=current(c);return j&&j->env_initialized?&j->env:&c->env;}
static exprtk_value_t fail(turbo_script_ctx_t*c,turbo_script_error_code_t e,const char*m){ts_task_job_t*j=current(c);exprtk_env_t*v=ts_task_execution_env(c);if(j){j->native_failed=1;copy_error(j->error,sizeof(j->error),m);}else ctx_error(c,e,m);v->aborted=1;copy_error(v->error_msg,sizeof(v->error_msg),m);return exprtk_val_num(0);}
static int as_u64(exprtk_value_t v,uint64_t*out){if(v.type==EXPRTK_VAL_INTEGER&&v.data.integer>=0){*out=(uint64_t)v.data.integer;return 0;}if(v.type==EXPRTK_VAL_NUMBER&&isfinite(v.data.number)&&v.data.number>=0&&floor(v.data.number)==v.data.number&&v.data.number<=(double)UINT64_MAX){*out=(uint64_t)v.data.number;return 0;}return -1;}
static int as_id(exprtk_value_t v,int64_t*out){uint64_t n;if(as_u64(v,&n)||!n||n>INT64_MAX)return -1;*out=(int64_t)n;return 0;}
static ts_task_job_t *find_locked(ts_task_scheduler_t*s,int64_t id){for(size_t i=0;i<s->capacity;i++)if(s->jobs[i].id==id&&s->jobs[i].state!=TS_TASK_EMPTY)return&s->jobs[i];return NULL;}
static void deactivate_locked(ts_task_scheduler_t*s,ts_task_job_t*j){if(j->active){j->active=0;if(s->active_count)s->active_count--;}}
static void release_callback(ts_task_job_t*j){if(j->callback.type==EXPRTK_VAL_FUNCTION&&j->callback.ownership==EXPRTK_VALUE_OWNED&&j->callback.data.function.closure_env){exprtk_env_release(j->callback.data.function.closure_env);j->callback.data.function.closure_env=NULL;j->callback.ownership=EXPRTK_VALUE_BORROWED;}}
static void retain_callback(ts_task_job_t*j){if(j->callback.type==EXPRTK_VAL_FUNCTION&&j->callback.data.function.closure_env){exprtk_env_retain(j->callback.data.function.closure_env);j->callback.ownership=EXPRTK_VALUE_OWNED;}}
static void reset_job(ts_task_job_t*j){ts_task_scheduler_t*s=j->scheduler;if(j->env_initialized){if(exprtk_value_is_object_like(&j->result))exprtk_map_free(&j->result);exprtk_env_free(&j->env);}release_callback(j);memset(j,0,sizeof(*j));j->magic=TS_TASK_MAGIC;j->scheduler=s;}
static void init_env(ts_task_job_t*j,turbo_script_ctx_t*c){exprtk_env_init_child(&j->env,&c->env);j->env.eval_node=c->env.eval_node;j->env.exec_script_body=c->env.exec_script_body;j->env.max_recursion=c->env.max_recursion;j->env.max_loop_iterations=c->env.max_loop_iterations;j->env.max_nodes=c->env.max_nodes;j->env.max_external_value_bytes=c->memory_policy.max_external_value_bytes;j->env_initialized=1;}
static void attach_closure(turbo_script_ctx_t*c,exprtk_value_t cb){exprtk_env_t*r=cb.data.function.closure_env;if(!r)return;while(r->parent&&r->parent!=&c->env)r=r->parent;if(r!=&c->env&&!r->parent)r->parent=&c->env;}
static void capture_error(exprtk_env_t*e,char*d,size_t n){if(e->error_msg[0])copy_error(d,n,e->error_msg);else copy_error(d,n,"task callback failed");}
static int is_cancelled(ts_task_job_t*j){int r;salts_mutex_lock(&j->scheduler->mutex);r=j->cancelled;salts_mutex_unlock(&j->scheduler->mutex);return r;}
static int request_cancel(ts_task_job_t*j){salts_coro_executor_await_t h={0};int wake=0;if(!j||!j->scheduler)return SALTS_EINVAL;salts_mutex_lock(&j->scheduler->mutex);if(terminal(j->state)||j->cancelled){salts_mutex_unlock(&j->scheduler->mutex);return SALTS_EALREADY;}j->cancelled=1;j->state=TS_TASK_CANCELLING;if(j->await_active){h=j->await_handle;wake=1;}salts_mutex_unlock(&j->scheduler->mutex);if(wake)(void)salts_coro_executor_await_complete(j->scheduler->ctx->executor,h,SALTS_ECANCELED);return SALTS_OK;}
static void finish(ts_task_job_t*j,int forced){ts_task_scheduler_t*s=j->scheduler;turbo_script_ctx_t*c=s->ctx;int cancelled=forced||is_cancelled(j);int failed=j->native_failed||j->env.aborted||j->env.flow!=exprtk_FLOW_NORMAL;if(cancelled)copy_error(j->error,sizeof(j->error),"task was cancelled");else if(failed&&!j->error[0])capture_error(&j->env,j->error,sizeof(j->error));release_callback(j);memset(&j->callback,0,sizeof(j->callback));exprtk_env_sweep_closures(&c->env);salts_mutex_lock(&s->mutex);j->await_active=0;j->state=cancelled?TS_TASK_CANCELLED:(failed?TS_TASK_FAILED:TS_TASK_COMPLETED);deactivate_locked(s,j);ts_task_completion_fn done=j->completion;void*a=j->completion_arg;char e[TS_TASK_ERROR_SIZE];copy_error(e,sizeof(e),j->error);int drop=j->auto_release;salts_mutex_unlock(&s->mutex);if(done)done(c,cancelled,e,a);if(drop)reset_job(j);}
static void run_task(coro_t*co,void*arg){ts_task_job_t*j=arg;turbo_script_ctx_t*c;if(!j||!j->scheduler)return;(void)co;c=j->scheduler->ctx;ts_task_current_job=j;salts_mutex_lock(&j->scheduler->mutex);if(j->scheduler->closing||atomic_load(&c->closing)||j->cancelled||j->state!=TS_TASK_SCHEDULED){j->cancelled=1;salts_mutex_unlock(&j->scheduler->mutex);finish(j,1);ts_task_current_job=NULL;return;}j->state=TS_TASK_RUNNING;salts_mutex_unlock(&j->scheduler->mutex);j->env.aborted=0;j->env.flow=exprtk_FLOW_NORMAL;j->env.curr_nodes=j->env.curr_loop_iterations=j->env.curr_recursion=0;j->env.error_msg[0]='\0';j->result=exprtk_call_function_value(j->callback,0,NULL,&j->env);if(mem_pool_total_used(&j->env.arena)>c->memory_policy.max_task_bytes){j->native_failed=1;j->env.aborted=1;copy_error(j->error,sizeof(j->error),"task result exceeded the configured memory quota");}finish(j,0);ts_task_current_job=NULL;}
static void cancel_task(void*arg,int status){ts_task_job_t*j=arg;(void)status;if(!j||!j->scheduler)return;ts_task_current_job=j;j->cancelled=1;finish(j,1);ts_task_current_job=NULL;}
static int spawn(turbo_script_ctx_t*c,exprtk_value_t cb,ts_task_completion_fn done,void*a,int drop,int64_t*out){ts_task_scheduler_t*s=c?c->task_scheduler:NULL;ts_task_job_t*j=NULL;if(!s||!c->executor){fail(c,TURBO_SCRIPT_ERROR_STATE,"task.spawn: executor is unavailable");return -1;}salts_mutex_lock(&s->mutex);if(s->closing||atomic_load(&c->closing)){salts_mutex_unlock(&s->mutex);fail(c,TURBO_SCRIPT_ERROR_STATE,"task.spawn: context is closing");return -1;}for(size_t i=0;i<s->capacity;i++)if(s->jobs[i].state==TS_TASK_EMPTY){j=&s->jobs[i];j->state=TS_TASK_RESERVED;break;}if(!j){salts_mutex_unlock(&s->mutex);fail(c,TURBO_SCRIPT_ERROR_STATE,"task.spawn: registry capacity exhausted; release completed tasks");return -1;}j->id=++s->next_id;if(j->id<=0)j->id=s->next_id=1;j->callback=cb;retain_callback(j);j->completion=done;j->completion_arg=a;j->auto_release=drop;j->result=exprtk_val_num(0);j->active=1;j->state=TS_TASK_SCHEDULED;s->active_count++;*out=j->id;salts_mutex_unlock(&s->mutex);attach_closure(c,cb);init_env(j,c);salts_coro_executor_task_t t={run_task,cancel_task,NULL,j};int rc=salts_coro_executor_try_submit_to(c->executor,0,&t);if(rc==SALTS_OK)return 0;salts_mutex_lock(&s->mutex);deactivate_locked(s,j);j->state=TS_TASK_EMPTY;salts_mutex_unlock(&s->mutex);reset_job(j);fail(c,rc==SALTS_ENOMEM?TURBO_SCRIPT_ERROR_OOM:TURBO_SCRIPT_ERROR_STATE,rc==SALTS_ENOBUFS?"task.spawn: executor queue is full":"task.spawn: executor rejected the task");return -1;}
static int wait_for(ts_task_job_t*j,uint32_t ms){if(!ms)return salts_coro_executor_yield();salts_coro_executor_await_t h={0};int status=0,rc=salts_coro_executor_await_begin(&h);if(rc)return rc;salts_mutex_lock(&j->scheduler->mutex);j->await_handle=h;j->await_active=1;j->state=j->cancelled?TS_TASK_CANCELLING:TS_TASK_WAITING;int cancelled=j->cancelled;salts_mutex_unlock(&j->scheduler->mutex);if(cancelled)(void)salts_coro_executor_await_complete(j->scheduler->ctx->executor,h,SALTS_ECANCELED);rc=salts_coro_executor_await_for(h,ms,&status);salts_mutex_lock(&j->scheduler->mutex);j->await_active=0;if(!terminal(j->state)&&!j->cancelled)j->state=TS_TASK_RUNNING;cancelled=j->cancelled;salts_mutex_unlock(&j->scheduler->mutex);return rc?rc:(cancelled||status==SALTS_ECANCELED?SALTS_ECANCELED:SALTS_OK);}
static exprtk_value_t fn_spawn(size_t n,exprtk_value_t*a,exprtk_env_t*e,void*d){turbo_script_ctx_t*c=d;int64_t id;(void)e;if(n!=1||a[0].type!=EXPRTK_VAL_FUNCTION)return fail(c,TURBO_SCRIPT_ERROR_ARGUMENT,"task.spawn: expected one function argument");return spawn(c,a[0],NULL,NULL,0,&id)?exprtk_val_num(0):exprtk_val_int(id);}
static exprtk_value_t fn_yield(size_t n,exprtk_value_t*a,exprtk_env_t*e,void*d){turbo_script_ctx_t*c=d;ts_task_job_t*j=current(c);(void)a;(void)e;if(n)return fail(c,TURBO_SCRIPT_ERROR_ARGUMENT,"task.yield: expected no arguments");if(!j)return fail(c,TURBO_SCRIPT_ERROR_STATE,"task.yield: may only be called from task.spawn callback");if(is_cancelled(j))return fail(c,TURBO_SCRIPT_ERROR_CANCELLED,"task was cancelled");if(salts_coro_executor_yield()!=SALTS_OK)return fail(c,TURBO_SCRIPT_ERROR_STATE,"task.yield: executor yield failed");return is_cancelled(j)?fail(c,TURBO_SCRIPT_ERROR_CANCELLED,"task was cancelled"):exprtk_val_num(0);}
static exprtk_value_t fn_sleep(size_t n,exprtk_value_t*a,exprtk_env_t*e,void*d){turbo_script_ctx_t*c=d;ts_task_job_t*j=current(c);uint64_t ms;(void)e;if(n!=1||as_u64(a[0],&ms)||ms>TS_TASK_MAX_SLEEP_MS)return fail(c,TURBO_SCRIPT_ERROR_ARGUMENT,"task.sleep: expected milliseconds between 0 and 4294967294");if(!j)return fail(c,TURBO_SCRIPT_ERROR_STATE,"task.sleep: may only be called from task.spawn callback");int rc=wait_for(j,(uint32_t)ms);return rc==SALTS_OK?exprtk_val_num(0):fail(c,rc==SALTS_ECANCELED?TURBO_SCRIPT_ERROR_CANCELLED:TURBO_SCRIPT_ERROR_STATE,rc==SALTS_ECANCELED?"task was cancelled":"task.sleep: executor await failed");}
static exprtk_value_t fn_status(size_t n,exprtk_value_t*a,exprtk_env_t*e,void*d){turbo_script_ctx_t*c=d;int64_t id;const char*r="invalid";(void)e;if(n!=1||as_id(a[0],&id))return fail(c,TURBO_SCRIPT_ERROR_ARGUMENT,"task.status: expected a positive task id");salts_mutex_lock(&c->task_scheduler->mutex);ts_task_job_t*j=find_locked(c->task_scheduler,id);if(j)r=state_name(j->state);salts_mutex_unlock(&c->task_scheduler->mutex);return exprtk_val_str(vstr_from_cstr(r));}
static exprtk_value_t fn_result(size_t n,exprtk_value_t*a,exprtk_env_t*e,void*d){turbo_script_ctx_t*c=d;int64_t id;(void)e;if(n!=1||as_id(a[0],&id))return fail(c,TURBO_SCRIPT_ERROR_ARGUMENT,"task.result: expected a positive task id");salts_mutex_lock(&c->task_scheduler->mutex);ts_task_job_t*j=find_locked(c->task_scheduler,id);if(!j||j->state!=TS_TASK_COMPLETED){salts_mutex_unlock(&c->task_scheduler->mutex);return fail(c,TURBO_SCRIPT_ERROR_STATE,"task.result: task is not complete");}exprtk_value_t v=exprtk_value_clone_to_env(j->result,ts_task_execution_env(c));salts_mutex_unlock(&c->task_scheduler->mutex);return v;}
static exprtk_value_t fn_join(size_t n,exprtk_value_t*a,exprtk_env_t*e,void*d){turbo_script_ctx_t*c=d;ts_task_job_t*self=current(c);int64_t id;(void)e;if(n!=1||as_id(a[0],&id))return fail(c,TURBO_SCRIPT_ERROR_ARGUMENT,"task.join: expected a positive task id");if(!self)return fail(c,TURBO_SCRIPT_ERROR_STATE,"task.join: may only be called from task.spawn callback");for(;;){salts_mutex_lock(&c->task_scheduler->mutex);ts_task_job_t*j=find_locked(c->task_scheduler,id);if(!j||j==self){salts_mutex_unlock(&c->task_scheduler->mutex);return fail(c,TURBO_SCRIPT_ERROR_ARGUMENT,"task.join: invalid task id");}if(terminal(j->state)){if(j->state==TS_TASK_COMPLETED){exprtk_value_t v=exprtk_value_clone_to_env(j->result,&self->env);salts_mutex_unlock(&c->task_scheduler->mutex);return v;}char m[TS_TASK_ERROR_SIZE];copy_error(m,sizeof(m),j->error[0]?j->error:"task was cancelled");salts_mutex_unlock(&c->task_scheduler->mutex);return fail(c,j->state==TS_TASK_CANCELLED?TURBO_SCRIPT_ERROR_CANCELLED:TURBO_SCRIPT_ERROR_RUNTIME,m);}salts_mutex_unlock(&c->task_scheduler->mutex);int rc=wait_for(self,1);if(rc)return fail(c,rc==SALTS_ECANCELED?TURBO_SCRIPT_ERROR_CANCELLED:TURBO_SCRIPT_ERROR_STATE,rc==SALTS_ECANCELED?"task was cancelled":"task.join: executor await failed");}}
static exprtk_value_t fn_cancel(size_t n,exprtk_value_t*a,exprtk_env_t*e,void*d){turbo_script_ctx_t*c=d;int64_t id;(void)e;if(n!=1||as_id(a[0],&id))return fail(c,TURBO_SCRIPT_ERROR_ARGUMENT,"task.cancel: expected a positive task id");salts_mutex_lock(&c->task_scheduler->mutex);ts_task_job_t*j=find_locked(c->task_scheduler,id);salts_mutex_unlock(&c->task_scheduler->mutex);return exprtk_val_bool(j&&request_cancel(j)==SALTS_OK);}
static exprtk_value_t fn_release(size_t n,exprtk_value_t*a,exprtk_env_t*e,void*d){turbo_script_ctx_t*c=d;int64_t id;(void)e;if(n!=1||as_id(a[0],&id))return fail(c,TURBO_SCRIPT_ERROR_ARGUMENT,"task.release: expected a positive task id");salts_mutex_lock(&c->task_scheduler->mutex);ts_task_job_t*j=find_locked(c->task_scheduler,id);if(!j||!terminal(j->state)){salts_mutex_unlock(&c->task_scheduler->mutex);return exprtk_val_bool(0);}salts_mutex_unlock(&c->task_scheduler->mutex);reset_job(j);return exprtk_val_bool(1);}
static exprtk_value_t fn_active(size_t n,exprtk_value_t*a,exprtk_env_t*e,void*d){(void)a;(void)e;turbo_script_ctx_t*c=d;return n?fail(c,TURBO_SCRIPT_ERROR_ARGUMENT,"task.active_count: expected no arguments"):exprtk_val_int((int64_t)turbo_script_task_active_count(c));}
int ts_task_scheduler_init(turbo_script_ctx_t*c,size_t cap){if(!c||!cap||cap>TS_TASK_MAX_CAPACITY)return -1;ts_task_scheduler_t*s=calloc(1,sizeof(*s));if(!s)return -1;s->jobs=calloc(cap,sizeof(*s->jobs));if(!s->jobs){free(s);return -1;}s->ctx=c;s->capacity=cap;salts_mutex_init(&s->mutex);for(size_t i=0;i<cap;i++){s->jobs[i].magic=TS_TASK_MAGIC;s->jobs[i].scheduler=s;}c->task_scheduler=s;return 0;}
void ts_task_scheduler_shutdown(turbo_script_ctx_t*c){if(!c||!c->task_scheduler)return;ts_task_scheduler_t*s=c->task_scheduler;salts_mutex_lock(&s->mutex);s->closing=1;salts_mutex_unlock(&s->mutex);for(size_t i=0;i<s->capacity;i++)(void)request_cancel(&s->jobs[i]);}
void ts_task_scheduler_destroy(turbo_script_ctx_t*c){if(!c||!c->task_scheduler)return;ts_task_scheduler_t*s=c->task_scheduler;for(size_t i=0;i<s->capacity;i++)reset_job(&s->jobs[i]);salts_mutex_destroy(&s->mutex);free(s->jobs);free(s);c->task_scheduler=NULL;}
void ts_task_register_functions(turbo_script_ctx_t*c){exprtk_env_register_func(&c->env,"task.spawn",fn_spawn,c);exprtk_env_register_func(&c->env,"task.yield",fn_yield,c);exprtk_env_register_func(&c->env,"task.sleep",fn_sleep,c);exprtk_env_register_func(&c->env,"task.join",fn_join,c);exprtk_env_register_func(&c->env,"task.status",fn_status,c);exprtk_env_register_func(&c->env,"task.result",fn_result,c);exprtk_env_register_func(&c->env,"task.cancel",fn_cancel,c);exprtk_env_register_func(&c->env,"task.release",fn_release,c);exprtk_env_register_func(&c->env,"task.active_count",fn_active,c);}
int ts_task_spawn_managed(turbo_script_ctx_t*c,exprtk_value_t cb,ts_task_completion_fn f,void*a,int64_t*id){return !c||!f||!id?SALTS_EINVAL:(spawn(c,cb,f,a,1,id)?SALTS_EINVAL:SALTS_OK);}int ts_task_cancel_managed(turbo_script_ctx_t*c,int64_t id){if(!c||!c->task_scheduler)return SALTS_EINVAL;salts_mutex_lock(&c->task_scheduler->mutex);ts_task_job_t*j=find_locked(c->task_scheduler,id);salts_mutex_unlock(&c->task_scheduler->mutex);return j?request_cancel(j):SALTS_EALREADY;}
size_t ts_task_memory_used(turbo_script_ctx_t*c){size_t n=0;if(!c||!c->task_scheduler)return 0;ts_task_scheduler_t*s=c->task_scheduler;salts_mutex_lock(&s->mutex);for(size_t i=0;i<s->capacity;i++)if(s->jobs[i].env_initialized)n+=mem_pool_total_used(&s->jobs[i].env.arena);salts_mutex_unlock(&s->mutex);return n;}size_t ts_task_memory_max_used(turbo_script_ctx_t*c){size_t n=0;if(!c||!c->task_scheduler)return 0;ts_task_scheduler_t*s=c->task_scheduler;salts_mutex_lock(&s->mutex);for(size_t i=0;i<s->capacity;i++)if(s->jobs[i].env_initialized){size_t x=mem_pool_total_used(&s->jobs[i].env.arena);if(x>n)n=x;}salts_mutex_unlock(&s->mutex);return n;}
int turbo_script_set_task_capacity(turbo_script_ctx_t*c,size_t cap){if(!c||!c->task_scheduler||!cap||cap>TS_TASK_MAX_CAPACITY){if(c)ctx_error(c,TURBO_SCRIPT_ERROR_ARGUMENT,"task capacity must be between 1 and 65536");return -1;}if(turbo_script_task_active_count(c)){ctx_error(c,TURBO_SCRIPT_ERROR_STATE,"cannot resize task registry while tasks are active");return -1;}ts_task_scheduler_destroy(c);return ts_task_scheduler_init(c,cap)?-1:0;}size_t ts_task_scheduler_capacity(turbo_script_ctx_t*c){return c&&c->task_scheduler?c->task_scheduler->capacity:0;}size_t turbo_script_task_active_count(turbo_script_ctx_t*c){if(!c||!c->task_scheduler)return 0;ts_task_scheduler_t*s=c->task_scheduler;salts_mutex_lock(&s->mutex);size_t n=s->active_count;salts_mutex_unlock(&s->mutex);return n;}size_t turbo_script_task_failed_count(turbo_script_ctx_t*c){size_t n=0;if(!c||!c->task_scheduler)return 0;ts_task_scheduler_t*s=c->task_scheduler;salts_mutex_lock(&s->mutex);for(size_t i=0;i<s->capacity;i++)n+=s->jobs[i].state==TS_TASK_FAILED;salts_mutex_unlock(&s->mutex);return n;}
